logging:
  level:
    org.zalando.logbook.Logbook: TRACE

spring:
  application:
    name: spring-boot-ai-logging-demo
  ai:
    openai:
      api-key: "<your-openrouter-api-key>"
      base-url: 'https://openrouter.ai/api'
      chat:
        options:
          model: google/gemini-2.0-flash-exp:free

